### Exporter les données pour le programme C sous nordic

In [1]:
import pandas as pd

In [2]:
test_data = pd.read_csv("test_data.csv", low_memory=False)

In [3]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21841 entries, 0 to 21840
Data columns (total 47 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FIT101         21841 non-null  float64
 1   LIT101         21841 non-null  float64
 2   MV101          21841 non-null  int64
 3   P101           21841 non-null  int64
 4   P102           21841 non-null  int64
 5   AIT201         21841 non-null  float64
 6   AIT202         21841 non-null  float64
 7   AIT203         21841 non-null  float64
 8   FIT201         21841 non-null  float64
 9   P201           21841 non-null  int64
 10  P202           21841 non-null  int64
 11  P204           21841 non-null  int64
 12  P205           21841 non-null  int64
 13  DPIT301        21841 non-null  float64
 14  FIT301         21841 non-null  float64
 15  LIT301         21841 non-null  float64
 16  MV301          21841 non-null  int64
 17  MV302          21841 non-null  int64
 18  MV303          21841 non-null  int64
 19  MV304          21841 non-null  int64
 20  P301           21841 non-null  int64
 21  P302           21841 non-null  int64
 22  AIT401         21841 non-null  float64
 23  AIT402         21841 non-null  float64
 24  FIT401         21841 non-null  float64
 25  LIT401         21841 non-null  float64
 26  P401           21841 non-null  int64
 27  P402           21841 non-null  int64
 28  P403           21841 non-null  int64
 29  P404           21841 non-null  int64
 30  AIT501         21841 non-null  float64
 31  AIT502         21841 non-null  float64
 32  AIT503         21841 non-null  float64
 33  AIT504         21841 non-null  float64
 34  FIT501         21841 non-null  float64
 35  FIT502         21841 non-null  float64
 36  FIT503         21841 non-null  float64
 37  FIT504         21841 non-null  float64
 38  P502           21841 non-null  int64
 39  PIT501         21841 non-null  float64
 40  PIT502         21841 non-null  float64
 41  PIT503         21841 non-null  float64
 42  FIT601         21841 non-null  float64
 43  P601           21841 non-null  int64
 44  P602           21841 non-null  int64
 45  P603           21841 non-null  int64
 46  Normal/Attack  21841 non-null  int64
dtypes: float64(25), int64(22)
memory usage: 7.8 MB

In [4]:
# Filtrer les données
# on veut 10 => '0' et 10 => '1'

normal_rows = test_data[test_data["Normal/Attack"] == 0].head(10)

# Sélectionner 10 lignes avec 'Normal/Attack' = 0
attack_rows = test_data[test_data["Normal/Attack"] == 1].head(10)

# Combiner les deux ensembles
selected_rows = pd.concat([normal_rows, attack_rows])
selected_rows.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 1 to 19
Data columns (total 47 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FIT101         20 non-null     float64
 1   LIT101         20 non-null     float64
 2   MV101          20 non-null     int64
 3   P101           20 non-null     int64
 4   P102           20 non-null     int64
 5   AIT201         20 non-null     float64
 6   AIT202         20 non-null     float64
 7   AIT203         20 non-null     float64
 8   FIT201         20 non-null     float64
 9   P201           20 non-null     int64
 10  P202           20 non-null     int64
 11  P204           20 non-null     int64
 12  P205           20 non-null     int64
 13  DPIT301        20 non-null     float64
 14  FIT301         20 non-null     float64
 15  LIT301         20 non-null     float64
 16  MV301          20 non-null     int64
 17  MV302          20 non-null     int64
 18  MV303          20 non-null     int64
 19  MV304          20 non-null     int64
 20  P301           20 non-null     int64
 21  P302           20 non-null     int64
 22  AIT401         20 non-null     float64
 23  AIT402         20 non-null     float64
 24  FIT401         20 non-null     float64
 25  LIT401         20 non-null     float64
 26  P401           20 non-null     int64
 27  P402           20 non-null     int64
 28  P403           20 non-null     int64
 29  P404           20 non-null     int64
 30  AIT501         20 non-null     float64
 31  AIT502         20 non-null     float64
 32  AIT503         20 non-null     float64
 33  AIT504         20 non-null     float64
 34  FIT501         20 non-null     float64
 35  FIT502         20 non-null     float64
 36  FIT503         20 non-null     float64
 37  FIT504         20 non-null     float64
 38  P502           20 non-null     int64
 39  PIT501         20 non-null     float64
 40  PIT502         20 non-null     float64
 41  PIT503         20 non-null     float64
 42  FIT601         20 non-null     float64
 43  P601           20 non-null     int64
 44  P602           20 non-null     int64
 45  P603           20 non-null     int64
 46  Normal/Attack  20 non-null     int64
dtypes: float64(25), int64(22)
memory usage: 7.5 KB

In [8]:
#separation des données
x_test, y_test = selected_rows.drop(columns=['Normal/Attack']), selected_rows['Normal/Attack']
print(x_test.shape)
print(y_test.shape)

(20, 46)
(20,)

In [9]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 1 to 19
Data columns (total 46 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   FIT101   20 non-null     float64
 1   LIT101   20 non-null     float64
 2   MV101    20 non-null     int64
 3   P101     20 non-null     int64
 4   P102     20 non-null     int64
 5   AIT201   20 non-null     float64
 6   AIT202   20 non-null     float64
 7   AIT203   20 non-null     float64
 8   FIT201   20 non-null     float64
 9   P201     20 non-null     int64
 10  P202     20 non-null     int64
 11  P204     20 non-null     int64
 12  P205     20 non-null     int64
 13  DPIT301  20 non-null     float64
 14  FIT301   20 non-null     float64
 15  LIT301   20 non-null     float64
 16  MV301    20 non-null     int64
 17  MV302    20 non-null     int64
 18  MV303    20 non-null     int64
 19  MV304    20 non-null     int64
 20  P301     20 non-null     int64
 21  P302     20 non-null     int64
 22  AIT401   20 non-null     float64
 23  AIT402   20 non-null     float64
 24  FIT401   20 non-null     float64
 25  LIT401   20 non-null     float64
 26  P401     20 non-null     int64
 27  P402     20 non-null     int64
 28  P403     20 non-null     int64
 29  P404     20 non-null     int64
 30  AIT501   20 non-null     float64
 31  AIT502   20 non-null     float64
 32  AIT503   20 non-null     float64
 33  AIT504   20 non-null     float64
 34  FIT501   20 non-null     float64
 35  FIT502   20 non-null     float64
 36  FIT503   20 non-null     float64
 37  FIT504   20 non-null     float64
 38  P502     20 non-null     int64
 39  PIT501   20 non-null     float64
 40  PIT502   20 non-null     float64
 41  PIT503   20 non-null     float64
 42  FIT601   20 non-null     float64
 43  P601     20 non-null     int64
 44  P602     20 non-null     int64
 45  P603     20 non-null     int64
dtypes: float64(25), int64(21)
memory usage: 7.3 KB

In [10]:
y_test.info()

<class 'pandas.core.series.Series'>
Int64Index: 20 entries, 1 to 19
Series name: Normal/Attack
Non-Null Count  Dtype
--------------  -----
20 non-null     int64
dtypes: int64(1)
memory usage: 320.0 bytes

In [12]:
#transformer en liste

x_test_c = x_test.to_numpy(dtype=float)
y_test_c = y_test.to_numpy(dtype=float)

20

In [14]:
# Générer le code pour C
x_test_c_code = "float x_test_c[20][45] = {\n" + ",\n".join(
    "{" + ", ".join(f"{x:.6f}" for x in row) + "}" for row in x_test_c
) + "\n};"

y_test_c_code = "int y_test_c[20] = {" + ", ".join(map(str, y_test_c)) + "};"

# Afficher le code pour C
print(x_test_c_code)
print(y_test_c_code)

float x_test_c[20][45] = {
{2.426416, 500.511900, 2.000000, 2.000000, 1.000000, 260.766500, 8.329146, 336.580400, 2.445904, 1.000000, 1.000000, 1.000000, 2.000000, 19.822010, 2.212856, 847.619200, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.808000, 179.441200, 1.697626, 911.958500, 1.000000, 2.000000, 1.000000, 1.000000, 7.854909, 173.468300, 260.542200, 10.766470, 1.703538, 1.257974, 0.743335, 0.310604, 1.000000, 255.527400, 1.537821, 194.309200, 0.000128, 1.000000, 1.000000, 1.000000},
{2.612497, 501.768000, 2.000000, 2.000000, 1.000000, 176.108700, 8.631634, 301.768800, 2.460257, 1.000000, 1.000000, 1.000000, 2.000000, 20.174150, 2.198636, 852.265400, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.803200, 144.116900, 1.722872, 900.576800, 1.000000, 2.000000, 1.000000, 1.000000, 7.798513, 137.554500, 269.706500, 16.188160, 1.730197, 1.294607, 0.732580, 0.306569, 1.000000, 248.942600, 1.025214, 187.339800, 0.000000, 1.000000, 1.000000, 1.000000},
{2.446274, 516.605500, 2.000000, 2.000000, 1.000000, 263.009500, 8.336196, 334.555200, 2.449492, 1.000000, 1.000000, 1.000000, 2.000000, 19.838020, 2.214137, 940.544100, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.808000, 179.466800, 1.701214, 932.376300, 1.000000, 2.000000, 1.000000, 1.000000, 7.854909, 173.263300, 264.932100, 10.920280, 1.708793, 1.234789, 0.743591, 0.310861, 1.000000, 256.168300, 1.601897, 194.934000, 0.000128, 1.000000, 1.000000, 1.000000},
{2.641642, 774.299900, 2.000000, 1.000000, 1.000000, 247.789000, 8.488080, 322.763400, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.106409, 0.000000, 1012.641000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 148.803200, 152.755700, 1.721078, 834.439900, 1.000000, 2.000000, 1.000000, 1.000000, 7.811972, 145.116600, 258.779800, 12.496800, 1.731735, 1.296016, 0.734885, 0.306761, 1.000000, 249.215000, 1.025214, 187.932600, 0.000000, 1.000000, 1.000000, 1.000000},
{2.592960, 509.814800, 2.000000, 2.000000, 1.000000, 257.209700, 8.420790, 516.662400, 2.456156, 1.000000, 1.000000, 1.000000, 1.000000, 19.882840, 2.207731, 924.482500, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 0.000000, 181.312500, 1.695960, 897.616000, 1.000000, 2.000000, 1.000000, 1.000000, 7.859715, 169.136100, 271.212500, 10.881830, 1.700718, 1.234405, 0.746279, 0.310540, 1.000000, 258.395300, 1.441707, 196.904600, 0.000128, 1.000000, 1.000000, 1.000000},
{0.000000, 680.956800, 1.000000, 2.000000, 1.000000, 256.472700, 8.349654, 338.528600, 2.441803, 1.000000, 1.000000, 1.000000, 2.000000, 19.978870, 2.220542, 802.318400, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.803200, 185.798500, 1.699805, 839.092500, 1.000000, 2.000000, 1.000000, 1.000000, 7.833120, 173.878500, 255.319200, 10.612660, 1.709434, 1.254515, 0.739366, 0.308683, 1.000000, 254.582200, 1.041233, 193.540100, 0.000064, 1.000000, 1.000000, 1.000000},
{0.000000, 584.238000, 1.000000, 2.000000, 1.000000, 188.477300, 8.528133, 372.955700, 2.452440, 2.000000, 1.000000, 1.000000, 2.000000, 20.119730, 2.199020, 817.058200, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.812800, 161.112500, 1.703393, 330.761400, 1.000000, 2.000000, 1.000000, 1.000000, 7.567163, 147.603200, 249.615500, 13.419640, 1.712766, 1.301780, 0.735269, 0.308426, 1.000000, 249.583400, 1.025214, 187.724300, 0.000064, 1.000000, 1.000000, 1.000000},
{2.656055, 498.745500, 2.000000, 2.000000, 1.000000, 174.090000, 8.608883, 301.743100, 2.455772, 1.000000, 1.000000, 1.000000, 2.000000, 20.180550, 2.199020, 958.087700, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.808000, 145.065400, 1.720309, 927.339200, 1.000000, 2.000000, 1.000000, 1.000000, 7.786016, 138.733700, 265.540900, 16.188160, 1.730838, 1.271295, 0.732836, 0.306633, 1.000000, 248.814400, 0.816967, 187.179600, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 812.610600, 1.000000, 1.000000, 1.000000, 182.549300, 8.660472, 301.640600, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.987963, 0.000000, 1008.235000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 148.808000, 147.269900, 1.710826, 807.216100, 1.000000, 2.000000, 1.000000, 1.000000, 7.771597, 139.400100, 257.177600, 13.842600, 1.717124, 1.285769, 0.734885, 0.306313, 1.000000, 251.922600, 0.800948, 189.727000, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 562.923800, 1.000000, 2.000000, 1.000000, 265.444800, 8.347411, 330.017900, 2.435267, 1.000000, 1.000000, 1.000000, 2.000000, 2.202446, 0.000000, 905.777400, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 148.803200, 162.496800, 1.735687, 936.682900, 1.000000, 2.000000, 1.000000, 1.000000, 7.888875, 148.449100, 273.872100, 13.458090, 1.747501, 1.294607, 0.728867, 0.304583, 1.000000, 246.699600, 1.169384, 186.394500, 0.000000, 1.000000, 1.000000, 1.000000},
{2.606412, 496.154800, 2.000000, 2.000000, 1.000000, 190.464000, 8.539028, 325.583200, 2.442060, 1.000000, 1.000000, 1.000000, 2.000000, 20.007680, 2.197739, 830.676500, 1.000000, 2.000000, 1.000000, 1.000000, 1.000000, 2.000000, 148.808000, 148.756700, 1.715567, 600.000000, 1.000000, 2.000000, 1.000000, 1.000000, 7.761984, 142.425000, 261.535500, 14.611640, 1.726224, 1.294479, 0.730020, 0.308298, 1.000000, 247.997300, 0.816967, 186.570800, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 812.963900, 1.000000, 1.000000, 1.000000, 198.154300, 8.524929, 370.187100, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.035982, 0.000000, 1015.124000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.808000, 325.249900, 0.000000, 248.359400, 1.000000, 1.000000, 1.000000, 1.000000, 7.434184, 185.901000, 269.994900, 15.688280, 0.001025, 0.001153, 0.001152, 0.000000, 1.000000, 9.660984, 0.000000, 3.252371, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 814.102200, 1.000000, 1.000000, 1.000000, 188.669600, 8.612728, 330.658800, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.010372, 0.000000, 1015.885000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.803200, 309.612900, 0.000000, 245.936900, 1.000000, 1.000000, 1.000000, 1.000000, 7.639580, 242.937700, 266.694400, 15.188410, 0.000897, 0.001153, 0.000896, 0.000000, 1.000000, 10.285820, 0.000000, 3.941297, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 812.649800, 1.000000, 1.000000, 1.000000, 192.931300, 8.582607, 355.037200, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.010372, 0.000000, 1015.365000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.808000, 332.325000, 0.000000, 247.282700, 1.000000, 1.000000, 1.000000, 1.000000, 7.512689, 223.455500, 268.168400, 15.611380, 0.000769, 0.001153, 0.000896, 0.000000, 1.000000, 10.013460, 0.000000, 3.733017, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 812.767600, 1.000000, 1.000000, 1.000000, 192.931300, 8.593502, 349.115600, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.010372, 0.000000, 1015.645000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.808000, 330.171800, 0.000000, 247.590400, 1.000000, 1.000000, 1.000000, 1.000000, 7.541849, 236.529100, 267.687800, 15.534480, 0.000897, 0.001153, 0.000896, 0.000000, 1.000000, 10.061520, 0.000000, 3.733017, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 814.534000, 1.000000, 1.000000, 1.000000, 193.251700, 8.551846, 363.881000, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.032781, 0.000000, 1014.524000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.812800, 331.171500, 0.000000, 247.744200, 1.000000, 1.000000, 1.000000, 1.000000, 7.469110, 201.076600, 269.225800, 15.726740, 0.000897, 0.001153, 0.001024, 0.000000, 1.000000, 9.773135, 0.000000, 3.492694, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 813.434900, 1.000000, 1.000000, 1.000000, 192.867200, 8.583569, 356.062600, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.003969, 0.000000, 1014.924000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.808000, 332.350700, 0.000000, 246.936700, 1.000000, 1.000000, 1.000000, 1.000000, 7.504999, 221.020200, 268.168400, 15.688280, 0.000897, 0.001153, 0.000896, 0.000000, 1.000000, 10.013460, 0.000000, 3.733017, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 813.434900, 1.000000, 1.000000, 1.000000, 192.931300, 8.582607, 353.627300, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.010372, 0.000000, 1015.925000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.808000, 331.940500, 0.000000, 248.090200, 1.000000, 1.000000, 1.000000, 1.000000, 7.520059, 227.275100, 268.072300, 15.572930, 0.000897, 0.001153, 0.000896, 0.000000, 1.000000, 10.029480, 0.000000, 3.733017, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 813.120900, 1.000000, 1.000000, 1.000000, 195.815200, 8.535503, 367.675000, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 2.035982, 0.000000, 1014.964000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.808000, 328.377300, 0.000000, 246.436800, 1.000000, 1.000000, 1.000000, 1.000000, 7.448603, 191.156100, 269.706500, 15.496030, 0.001025, 0.001153, 0.001152, 0.000000, 1.000000, 9.580876, 0.000000, 3.412586, 0.000000, 1.000000, 1.000000, 1.000000},
{0.000000, 813.395600, 1.000000, 1.000000, 1.000000, 192.162300, 8.611446, 336.580400, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.997567, 0.000000, 1015.325000, 1.000000, 1.000000, 1.000000, 2.000000, 1.000000, 1.000000, 148.803200, 323.814400, 0.000000, 246.782900, 1.000000, 1.000000, 1.000000, 1.000000, 7.612984, 247.423700, 267.014900, 15.380670, 0.000897, 0.001153, 0.000896, 0.000000, 1.000000, 10.205720, 0.000000, 3.941297, 0.000000, 1.000000, 1.000000, 1.000000}
};
int y_test_c[20] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0};

In [15]:
# ecriture dans un fichier .c
# Écrire dans un fichier .c
with open("data_test_c.c", "w") as f:
    f.write("// Fichier généré contenant les tableaux x_test_c et y_test_c\n")
    f.write(x_test_c_code + "\n\n")
    f.write(y_test_c_code + "\n")

print("Les tableaux ont été écrits dans le fichier 'output.c'.")

Les tableaux ont été écrits dans le fichier 'output.c'.